# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: my-config
# data:
#   PORT_NO: "80"
#   API_BASE_URL: "testing.url.com"

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.metadata.name }}-html
data:
  index.html: |
    <html>
      <head><title>{{ .Values.envName }}</title></head>
      <body>
        <h1>{{ .Values.message }}</h1>
      </body>
    </html>
