metadata:
  name: myapp-dev

replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: "0.2.3"

args:
  - "-text=Hello from DEV Environment 🚀- version4DevBranch"

hpa:
  enabled: true
  min: 2
  max: 5

ingress:
  host: app.abulearning.in