metadata:
  name: myapp-dev

replicaCount: 1

image:
  repository: alpine
  tag: "3.19"

args:
  - "-text=Hello from DEV Alpine Environment 🚀- version01"

hpa:
  enabled: true
  min: 1
  max: 5

ingress:
  host: app.abulearning.in