apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: myapp-secret
  namespace: myapp-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: myapp-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: myapp/dev/app-config
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: myapp/dev/app-config
        property: DB_PASSWORD
